apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: git-ops
build:
  artifacts:
  - image: gcr.io/my-first-project-17342/my-gitops-image
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml
  
